{{- $hasSecret := false }}
{{- range .Values.webhooks }}{{ if .secret }}{{ $hasSecret = true }}{{ end }}{{ end }}
{{- if $hasSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: nodevitals-webhooks
  labels:
    app.kubernetes.io/name: nodevitals
    app.kubernetes.io/component: webhooks
type: Opaque
stringData:
{{- range $i, $w := .Values.webhooks }}
{{- if $w.secret }}
  secret-{{ $i }}: {{ $w.secret | quote }}
{{- end }}
{{- end }}
{{- end }}
